@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.judge40.minecraft.bettermobgriefinggamerule;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
