@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.judge40.minecraft.bettermobgriefinggamerule.command;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
